### ISSUE TITLE
Kernel configuration settings of child workloads don't stack on parent kernel configuration

### ISSUE THREAD

**Issue by zhemao** [firesim/FireMarshal#138]
To reproduce, create a child workload of br-child.json with the following contents

    {
      "name" : "br-child",
      "base" : " br-base.json",
      "linux-config" : "br-child-kfrag"
    }

Create the `br-child-kfrag` file as well, but leave it blank. Build it with `marshal` and check `riscv-linux/.config` afterwards. You'll notice that things set in `br-base/linux-config` like `CONFIG_CMDLINE` are not set.

**Comment by NathanTP** [comment]
Fixed by #143
