### ISSUE TITLE
Corrupt file system when using OpenSBI with non-default initramfs

### ISSUE THREAD

**Issue by alonamid** [firesim/FireMarshal#163]
I'm summarizing the bug investigation and proposal solution by @a0u :

By default, FW_PAYLOAD_FDT_ADDR in OpenSBI is hardcoded to 0x82200000.
(https://github.com/riscv/opensbi/blob/v0.8/platform/generic/config.mk#L31).

This must not overlap with the kernel image, otherwise the data section will be overwritten with a copy of the FDT that OpenSBI passes to the kernel.
Therefore, when we have an initramfs that's bigger than ~35 MB, there is a chance for file system corruption.
This happens quite often with a non-default initramfs.

Temporary hacky fixes include just increasing that offset to something like 0x20000000 (i.e, 512 MiB) to give the payload a more generous margin.
The better solution is to have FireMarshal override FW_PAYLOAD_FDT_ADDR based on the payload size.

**Comment by a0u** [comment]
The peculiarities of `FW_JUMP_FDT_ADDR` and memory map constraints are being discussed in riscv/opensbi#169.
