### ISSUE TITLE
changing buildroot config not propagating?

### ISSUE THREAD

**Issue by sagark** [firesim/FireMarshal#21]
It seems that if I change `wlutil/br/buildroot-config` to add a package and re-run `./marshal -v build workloads/br-base.json`, the rootfs is not rebuilt

**Comment by sagark** [comment]
`marshal clean` didn't help either. I had to basically just run it manually

**Comment by NathanTP** [comment]
Kindof fixed in #25. BR is now rebuilt every time. I'm not going to close this issue because we can still do better (rebuilding from scratch every time re-runs the whole build-chain which is painful for complex workloads with guest-init scripts).

**Comment by NathanTP** [comment]
resolved by #83
