### ISSUE TITLE
CPU Parallelism Question

### ISSUE THREAD

**Issue by abejgonzalez** [firesim/FireMarshal#221]
Should the following be changed to use `env['jlevel']`?
https://github.com/firesim/FireMarshal/blob/c5d6da8ffe0c8c5945c3fcdcaa0994d679e67ca5/boards/default/distros/br/br.py#L153

This seems like this PR should've matched the two (https://github.com/firesim/FireMarshal/pull/207)? Or is there a reason why these might/should be different?

**Comment by NathanTP** [comment]
Ya, makes sense:
https://github.com/firesim/FireMarshal/pull/222

**Comment by NathanTP** [comment]
Solved by #222
