### ISSUE TITLE
Build failure exits 0

### ISSUE THREAD

**Issue by timsnyder-siv** [firesim/FireMarshal#233]
https://github.com/firesim/FireMarshal/blob/17f45c509d20b44efa1998c8b0baa8508084197f/marshal#L146-L154

I'm guessing that the code above doesn't exit 1 immediately on a failed build because you want the other builds to still get run?  That makes sense but I would still expect it to eventually exit non-zero.  It seems like the `failCount` logic at the bottom of the main loop should be expanded to also handle `failCount` being incremented for builds.

Unless there is a solid reason not to, I'll submit a PR for this.  It's currently confusing to look at the output of FireSim CI when marshal fails to build as in https://github.com/firesim/firesim/runs/5648590907?check_suite_focus=true#step:3:42

**Comment by NathanTP** [comment]
Ya that makes sense to me.
