### ISSUE TITLE
"sed: no such file" when attempting to install riscv-tools

### ISSUE THREAD

**Issue by benjaminou4412** [firesim/FireMarshal#255]
Been trying to get Firemarshal up and running in the standalone setup, with the ultimate goal of getting some chipyard designs running on a VCU118. Conda seems to have installed correctly - I was able to pull up its version (22.9.0), and the initial steps of "conda env create . . . firemarshall" and "conda activate firemarshal" in a cleanly cloned FireMarshal directory seem to have gone well.

However, when I executed the next step, I got this:

```
conda install -n firemarshal -c ucb-bar riscv-tools
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ryan/ssd/miniforge3/envs/firemarshal

  added / updated specs:
    - riscv-tools


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    gmp-6.2.1                  |       h58526e2_0         806 KB  conda-forge
    mpc-1.2.1                  |       h9f54685_0         106 KB  conda-forge
    mpfr-4.1.0                 |       h9202a9a_1         2.6 MB  conda-forge
    riscv-tools-1.0.1          |0_h1234567_gdcdbcaf       152.9 MB  ucb-bar
    ------------------------------------------------------------
                                           Total:       156.4 MB

The following NEW packages will be INSTALLED:

  gmp                conda-forge/linux-64::gmp-6.2.1-h58526e2_0 None
  mpc                conda-forge/linux-64::mpc-1.2.1-h9f54685_0 None
  mpfr               conda-forge/linux-64::mpfr-4.1.0-h9202a9a_1 None
  riscv-tools        ucb-bar/linux-64::riscv-tools-1.0.1-0_h1234567_gdcdbcaf None


Proceed ([y]/n)? y


Downloading and Extracting Packages
gmp-6.2.1            | 806 KB    | ########################################################## | 100% 
riscv-tools-1.0.1    | 152.9 MB  | ########################################################## | 100% 
mpfr-4.1.0           | 2.6 MB    | ########################################################## | 100% 
mpc-1.2.1            | 106 KB    | ########################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done
bash: sed: No such file or directory
bash: sed: No such file or directory
```

And I don't really have any idea how to debug this, since I have no idea what's invoking sed or what file sed is looking for. Also, this happened with fairly little delay after I initiated the command, and I know from experience riscv-tools takes a while to build and install, so I imagine this is a failed installation. In case it isn't, is there a way I could easily check?

**Comment by abejgonzalez** [comment]
This is a Chipyard issue so I would ask future questions there. However, this shouldn't be an issue IIRC. This is just a warning that needs to get removed. You can check if the toolchain is properly pulled in from conda-forge by running `echo $RISCV` in the environment that you installed the toolchain into (i.e. `firemarshal`)
