### ISSUE TITLE
[dev] Bad workdir relative path for symlink jsons

### ISSUE THREAD

**Issue by abejgonzalez** [firesim/FireMarshal#92]
When running `./marshal build example-workloads/sha3-linux.json` in `dev` I get the following error: 

```
ValueError: host-init script /home/centos/general/firemarshal/example-workloads/sha3/marshal-configs/sha3/build.sh not found.
```

`sha3-linux.json` is a symlink to a json in `marshal-configs` within the `workdir` which seems to indicate that the workdir is being specified from the `.json` location not where the symlink is.

**Comment by abejgonzalez** [comment]
The simple solution to this is to make the `workdir == ..` but I don't know if that is the preferred solution.

**Comment by NathanTP** [comment]
This is the expected behavior. Although I may reconsider the defaults now that marshal can build anywhere. It may make more sense to have the workdir default to '.'
